version: "3.9"
services:
  pebble-firmware:
    container_name: pebble-firmware
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - "./:/app/"
    command: ./app/dockerCompose.sh 